// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Custom storage proxy to support "Remember Me"
const customStorage = {
  getItem: (key: string) => {
    // Use the "Remember Me" flag to pick the correct storage,
    // avoiding cross-storage token leakage when a user toggles the setting.
    const rememberMe = localStorage.getItem('scubatrip-remember-me') !== 'false';
    return rememberMe ? localStorage.getItem(key) : sessionStorage.getItem(key);
  },
  setItem: (key: string, value: string) => {
    // Default to true if not set
    const rememberMe = localStorage.getItem('scubatrip-remember-me') !== 'false';
    if (rememberMe) {
      localStorage.setItem(key, value);
    } else {
      sessionStorage.setItem(key, value);
    }
  },
  removeItem: (key: string) => {
    localStorage.removeItem(key);
    sessionStorage.removeItem(key);
  },
};

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: customStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});